# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SMF_2nd_UI_R4.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(1173, 824)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridFrame = QtWidgets.QFrame(Dialog)
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalFrame = QtWidgets.QFrame(self.gridFrame)
        self.horizontalFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Ardu_Panel = QtWidgets.QVBoxLayout()
        self.Ardu_Panel.setObjectName("Ardu_Panel")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.Start_Button = QtWidgets.QPushButton(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Start_Button.setFont(font)
        self.Start_Button.setAutoDefault(False)
        self.Start_Button.setStyleSheet("background-color: rgba(255, 170, 255, 100);")
        self.Start_Button.setObjectName("Start_Button")
        self.gridLayout_8.addWidget(self.Start_Button, 0, 0, 1, 1)
        self.Stop_Button = QtWidgets.QPushButton(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Stop_Button.setFont(font)
        self.Stop_Button.setAutoDefault(False)
        self.Stop_Button.setStyleSheet("background-color: rgba(255, 170, 255, 100);")
        self.Stop_Button.setObjectName("Stop_Button")
        self.gridLayout_8.addWidget(self.Stop_Button, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_8, 0, 1, 1, 1)
        self.Ardu_Head = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Ardu_Head.setFont(font)
        self.Ardu_Head.setAutoFillBackground(True)
        self.Ardu_Head.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Ardu_Head.setAlignment(QtCore.Qt.AlignCenter)
        self.Ardu_Head.setObjectName("Ardu_Head")
        self.gridLayout_6.addWidget(self.Ardu_Head, 0, 0, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 2)
        self.Ardu_Panel.addLayout(self.gridLayout_6)
        self.line = QtWidgets.QFrame(self.horizontalFrame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Ardu_Panel.addWidget(self.line)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.NumExec = QtWidgets.QLineEdit(self.horizontalFrame)
        self.NumExec.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.NumExec.setFont(font)
        self.NumExec.setStyleSheet("background-color: rgba(170, 255, 255, 128);")
        self.NumExec.setObjectName("NumExec")
        self.verticalLayout_4.addWidget(self.NumExec)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 6, 4, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PatSize_Button = QtWidgets.QPushButton(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.PatSize_Button.setAutoDefault(False)
        self.PatSize_Button.setFont(font)
        self.PatSize_Button.setStyleSheet("background-color: rgba(255, 170, 255, 100);")
        self.PatSize_Button.setIconSize(QtCore.QSize(16, 16))
        self.PatSize_Button.setCheckable(True)
        self.PatSize_Button.setObjectName("PatSize_Button")
        self.verticalLayout_2.addWidget(self.PatSize_Button)
        self.PatSize_Info = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.PatSize_Info.setFont(font)
        self.PatSize_Info.setAutoFillBackground(True)
        self.PatSize_Info.setAlignment(QtCore.Qt.AlignCenter)
        self.PatSize_Info.setObjectName("PatSize_Info")
        self.verticalLayout_2.addWidget(self.PatSize_Info)
        self.verticalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 4, 2, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.X_LCD = QtWidgets.QLCDNumber(self.horizontalFrame)
        self.X_LCD.setAutoFillBackground(True)
        self.X_LCD.setDigitCount(6)
        self.X_LCD.setObjectName("X_LCD")
        self.gridLayout_4.addWidget(self.X_LCD, 1, 0, 1, 1)
        self.Y_LCD = QtWidgets.QLCDNumber(self.horizontalFrame)
        self.Y_LCD.setAutoFillBackground(True)
        self.Y_LCD.setDigitCount(6)
        self.Y_LCD.setProperty("value", 302.5)
        self.Y_LCD.setObjectName("Y_LCD")
        self.gridLayout_4.addWidget(self.Y_LCD, 1, 1, 1, 1)
        self.Y_Title = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Y_Title.setFont(font)
        self.Y_Title.setAutoFillBackground(True)
        self.Y_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Y_Title.setObjectName("Y_Title")
        self.gridLayout_4.addWidget(self.Y_Title, 0, 1, 1, 1)
        self.X_Title = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.X_Title.setFont(font)
        self.X_Title.setAutoFillBackground(True)
        self.X_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Title.setObjectName("X_Title")
        self.gridLayout_4.addWidget(self.X_Title, 0, 0, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.gridLayout_4.setRowStretch(0, 1)
        self.gridLayout_4.setRowStretch(1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 0, 4, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Pat_Info = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Pat_Info.setFont(font)
        self.Pat_Info.setAutoFillBackground(True)
        self.Pat_Info.setAlignment(QtCore.Qt.AlignCenter)
        self.Pat_Info.setObjectName("Pat_Info")
        self.verticalLayout.addWidget(self.Pat_Info)
        self.PatSize = QtWidgets.QLineEdit(self.horizontalFrame)
        self.PatSize.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.PatSize.setFont(font)
        self.PatSize.setAutoFillBackground(False)
        self.PatSize.setStyleSheet("background-color: rgba(170, 255, 255, 128);")
        self.PatSize.setText("")
        self.PatSize.setFrame(True)
        self.PatSize.setAlignment(QtCore.Qt.AlignCenter)
        self.PatSize.setDragEnabled(True)
        self.PatSize.setClearButtonEnabled(True)
        self.PatSize.setObjectName("PatSize")
        self.verticalLayout.addWidget(self.PatSize)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.verticalLayout, 4, 4, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Done_Info = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Done_Info.setFont(font)
        self.Done_Info.setAutoFillBackground(True)
        self.Done_Info.setAlignment(QtCore.Qt.AlignCenter)
        self.Done_Info.setObjectName("Done_Info")
        self.verticalLayout_7.addWidget(self.Done_Info)
        self.Done_Label = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Done_Label.setFont(font)
        self.Done_Label.setAutoFillBackground(False)
        self.Done_Label.setStyleSheet("background-color: rgb(255, 255, 255, 255);\n"
"")
        self.Done_Label.setFrameShape(QtWidgets.QFrame.Box)
        self.Done_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Done_Label.setObjectName("Done_Label")
        self.verticalLayout_7.addWidget(self.Done_Label)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 2, 4, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.gridLayout_2.addLayout(self.verticalLayout_9, 8, 4, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.NumExec_Button = QtWidgets.QPushButton(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.NumExec_Button.setAutoDefault(False)
        self.NumExec_Button.setFont(font)
        self.NumExec_Button.setStyleSheet("background-color: rgb(255, 170, 255,100);")
        self.NumExec_Button.setCheckable(True)
        self.NumExec_Button.setObjectName("NumExec_Button")
        self.verticalLayout_3.addWidget(self.NumExec_Button)
        self.Num_Info = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Num_Info.setFont(font)
        self.Num_Info.setAutoFillBackground(True)
        self.Num_Info.setAlignment(QtCore.Qt.AlignCenter)
        self.Num_Info.setObjectName("Num_Info")
        self.verticalLayout_3.addWidget(self.Num_Info)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 6, 2, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.horizontalFrame)
        self.pushButton.setAutoDefault(False)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgba(255, 170, 255, 100);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)
        self.label_2 = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 2, 2, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.CurPos_Button = QtWidgets.QPushButton(self.horizontalFrame)
        self.CurPos_Button.setAutoDefault(False)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.CurPos_Button.setFont(font)
        self.CurPos_Button.setStyleSheet("background-color: rgba(255, 170, 255, 100);")
        self.CurPos_Button.setCheckable(True)
        self.CurPos_Button.setChecked(False)
        self.CurPos_Button.setObjectName("CurPos_Button")
        self.verticalLayout_6.addWidget(self.CurPos_Button)
        self.CurPos_Info = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.CurPos_Info.setFont(font)
        self.CurPos_Info.setAutoFillBackground(True)
        self.CurPos_Info.setAlignment(QtCore.Qt.AlignCenter)
        self.CurPos_Info.setObjectName("CurPos_Info")
        self.verticalLayout_6.addWidget(self.CurPos_Info)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 2, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.RunTask_Button = QtWidgets.QPushButton(self.horizontalFrame)
        self.RunTask_Button.setAutoDefault(False)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.RunTask_Button.setFont(font)
        self.RunTask_Button.setStyleSheet("background-color: rgba(255, 170, 255, 100);")
        self.RunTask_Button.setObjectName("RunTask_Button")
        self.verticalLayout_8.addWidget(self.RunTask_Button)
        self.RunTask_Info = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.RunTask_Info.setFont(font)
        self.RunTask_Info.setAutoFillBackground(True)
        self.RunTask_Info.setAlignment(QtCore.Qt.AlignCenter)
        self.RunTask_Info.setObjectName("RunTask_Info")
        self.verticalLayout_8.addWidget(self.RunTask_Info)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 8, 2, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 6, 3, 1, 1)
        self.line_20 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.gridLayout_2.addWidget(self.line_20, 5, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 8, 0, 1, 1)
        self.Num_Title = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Num_Title.setFont(font)
        self.Num_Title.setAutoFillBackground(True)
        self.Num_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Num_Title.setObjectName("Num_Title")
        self.gridLayout_2.addWidget(self.Num_Title, 6, 0, 1, 1)
        self.CurPos_Title = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.CurPos_Title.setFont(font)
        self.CurPos_Title.setAutoFillBackground(True)
        self.CurPos_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.CurPos_Title.setObjectName("CurPos_Title")
        self.gridLayout_2.addWidget(self.CurPos_Title, 0, 0, 1, 1)
        self.PAT_Title = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PAT_Title.setFont(font)
        self.PAT_Title.setAutoFillBackground(True)
        self.PAT_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.PAT_Title.setObjectName("PAT_Title")
        self.gridLayout_2.addWidget(self.PAT_Title, 4, 0, 1, 1)
        self.Init_Title = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Init_Title.setFont(font)
        self.Init_Title.setAutoFillBackground(True)
        self.Init_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Init_Title.setObjectName("Init_Title")
        self.gridLayout_2.addWidget(self.Init_Title, 2, 0, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_2.addWidget(self.line_13, 1, 2, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_2.addWidget(self.line_9, 4, 1, 1, 1)
        self.line_23 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.gridLayout_2.addWidget(self.line_23, 7, 4, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_2.addWidget(self.line_11, 8, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_2.addWidget(self.line_7, 0, 1, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout_2.addWidget(self.line_16, 3, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 2, 3, 1, 1)
        self.line_17 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout_2.addWidget(self.line_17, 3, 4, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_2.addWidget(self.line_12, 1, 4, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_2.addWidget(self.line_15, 3, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 0, 3, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 4, 3, 1, 1)
        self.line_22 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.gridLayout_2.addWidget(self.line_22, 7, 2, 1, 1)
        self.line_21 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.gridLayout_2.addWidget(self.line_21, 7, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 8, 3, 1, 1)
        self.line_18 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout_2.addWidget(self.line_18, 5, 0, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_2.addWidget(self.line_14, 1, 0, 1, 1)
        self.line_19 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout_2.addWidget(self.line_19, 5, 2, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_2.addWidget(self.line_10, 6, 1, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_2.addWidget(self.line_8, 2, 1, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.Target_Img = QtWidgets.QLabel(self.horizontalFrame)
        self.Target_Img.setText("")
        self.Target_Img.setObjectName("Target_Img")
        self.gridLayout_10.addWidget(self.Target_Img, 4, 1, 1, 1)
        self.line_25 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.gridLayout_10.addWidget(self.line_25, 3, 1, 1, 1)
        self.line_26 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.gridLayout_10.addWidget(self.line_26, 5, 1, 1, 1)
        self.Orig_Img = QtWidgets.QLabel(self.horizontalFrame)
        self.Orig_Img.setText("")
        self.Orig_Img.setObjectName("Orig_Img")
        self.gridLayout_10.addWidget(self.Orig_Img, 0, 1, 1, 1)
        self.Orig_Label = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Orig_Label.setFont(font)
        self.Orig_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Orig_Label.setObjectName("Orig_Label")
        self.gridLayout_10.addWidget(self.Orig_Label, 2, 1, 1, 1)
        self.line_28 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_28.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.gridLayout_10.addWidget(self.line_28, 2, 0, 1, 1)
        self.line_29 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.gridLayout_10.addWidget(self.line_29, 4, 0, 1, 1)
        self.line_30 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_30.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.gridLayout_10.addWidget(self.line_30, 7, 0, 1, 1)
        self.line_27 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_27.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.gridLayout_10.addWidget(self.line_27, 0, 0, 1, 1)
        self.line_24 = QtWidgets.QFrame(self.horizontalFrame)
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.gridLayout_10.addWidget(self.line_24, 1, 1, 1, 1)
        self.Delta_LCD = QtWidgets.QLCDNumber(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Delta_LCD.setFont(font)
        self.Delta_LCD.setProperty("value", 12.5)
        self.Delta_LCD.setObjectName("Delta_LCD")
        self.gridLayout_10.addWidget(self.Delta_LCD, 7, 1, 1, 1)
        self.Delta_Label = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Delta_Label.setFont(font)
        self.Delta_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Delta_Label.setObjectName("Delta_Label")
        self.gridLayout_10.addWidget(self.Delta_Label, 6, 1, 1, 1)
        self.gridLayout_10.setRowStretch(0, 6)
        self.gridLayout_10.setRowStretch(1, 1)
        self.gridLayout_10.setRowStretch(2, 1)
        self.gridLayout_10.setRowStretch(3, 1)
        self.gridLayout_10.setRowStretch(4, 6)
        self.gridLayout_10.setRowStretch(5, 1)
        self.gridLayout_10.setRowStretch(6, 1)
        self.gridLayout_10.setRowStretch(7, 2)
        self.gridLayout_2.addLayout(self.gridLayout_10, 0, 5, 9, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_2.setColumnStretch(3, 1)
        self.gridLayout_2.setColumnStretch(4, 1)
        self.gridLayout_2.setColumnStretch(5, 1)
        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 1)
        self.gridLayout_2.setRowStretch(2, 1)
        self.gridLayout_2.setRowStretch(3, 1)
        self.gridLayout_2.setRowStretch(4, 1)
        self.gridLayout_2.setRowStretch(5, 1)
        self.gridLayout_2.setRowStretch(6, 1)
        self.gridLayout_2.setRowStretch(7, 1)
        self.gridLayout_2.setRowStretch(8, 1)
        self.Ardu_Panel.addLayout(self.gridLayout_2)
        self.Ardu_Panel.setStretch(2, 15)
        self.horizontalLayout.addLayout(self.Ardu_Panel)
        self.gridLayout.addWidget(self.horizontalFrame, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.gridFrame, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Program"))
        self.label.setText(_translate("Dialog", "SMART FACTORY \n"
"CONTROL PANEL"))
        self.Start_Button.setText(_translate("Dialog", "시작 \"버튼\""))
        self.Stop_Button.setText(_translate("Dialog", "정지 \"버튼\""))
        self.Ardu_Head.setText(_translate("Dialog", "모터 제어 통신"))
        self.PatSize_Button.setText(_translate("Dialog", "패턴 크기 입력 \"버튼\""))
        self.PatSize_Info.setText(_translate("Dialog", "위의 버튼을 클릭하면\n"
"\n"
"우측 입력란 활성화 됨"))
        self.Y_Title.setText(_translate("Dialog", "Y 좌표\n"
"(in mm)"))
        self.X_Title.setText(_translate("Dialog", "X 좌표\n"
"(in mm)"))
        self.Pat_Info.setText(_translate("Dialog", "패턴 크기 (폭 입력)\n"
"\n"
"최소: 50.7, 최대: 258.7\n"
"(소수점 첫째자리까지)"))
        self.Done_Info.setText(_translate("Dialog", "초기화 완료시\n"
"아래 박스에 \"완료\" 메세지 뜸"))
        self.Done_Label.setText(_translate("Dialog", "msg"))
        self.label_3.setText(_translate("Dialog", "TASK 완료 시\n"
"아래 박스에 \"완료\" 메세지 뜸"))
        self.label_4.setText(_translate("Dialog", "msg"))
        self.NumExec_Button.setText(_translate("Dialog", "시행 횟수 입력 \"버튼\""))
        self.Num_Info.setText(_translate("Dialog", "위의 버튼을 클릭하면\n"
"\n"
"우측 입력란 활성화 됨"))
        self.pushButton.setText(_translate("Dialog", "그리퍼 위치 설정 \"버튼\""))
        self.label_2.setText(_translate("Dialog", "그리퍼 arm 을 표시와 같이\n"
"\n"
"위치시키고 위의 버튼 클릭"))
        self.CurPos_Button.setText(_translate("Dialog", "현재 그리퍼 위치 표시 \"버튼\""))
        self.CurPos_Info.setText(_translate("Dialog", "위의 버튼을 누르면\n"
"\n"
"오른쪽 LCD 에 위치 표시"))
        self.RunTask_Button.setText(_translate("Dialog", "TASK 실행 \"버튼\""))
        self.RunTask_Info.setText(_translate("Dialog", "위의 버튼을 클릭하면\n"
"\n"
"입력한 회수만큼 실행됨"))
        self.label_5.setText(_translate("Dialog", "RUN\n"
"\n"
"TASK"))
        self.Num_Title.setText(_translate("Dialog", "# OF\n"
"\n"
"OPERATION"))
        self.CurPos_Title.setText(_translate("Dialog", "CURRENT\n"
"\n"
"POSITION"))
        self.PAT_Title.setText(_translate("Dialog", "PATTERN\n"
"\n"
"SIZE"))
        self.Init_Title.setText(_translate("Dialog", "INITIALIZE\n"
"\n"
"GRIPPER"))
        self.Orig_Label.setText(_translate("Dialog", "이미지"))
        self.Delta_Label.setText(_translate("Dialog", "(목표 위치 - 현재 위치 차이)"))
"""
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
"""